//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANLTWT3BANDIENTHOAIDIDONG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CAtegory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAtegory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int CategoryID { get; set; }

        [Required(ErrorMessage = "Tên danh m?c không ???c ?? tr?ng.")]
        [StringLength(50, ErrorMessage = "Tên danh m?c không ???c v??t quá 50 ký t?.")]
        [Display(Name = "Tên Danh M?c")]
        public string CategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
