//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANLTWT3BANDIENTHOAIDIDONG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customers = new HashSet<Customer>();
        }

        [Required(ErrorMessage = "Tên ??ng nh?p không ???c ?? tr?ng")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Tên ??ng nh?p ph?i t? 3 ??n 50 ký t?")]
        public string Username { get; set; }

        [Required(ErrorMessage = "M?t kh?u không ???c ?? tr?ng")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "M?t kh?u ph?i t? 6 ??n 20 ký t?")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Quy?n ng??i dùng không ???c ?? tr?ng")]
        public string UserRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
